[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
members = ["lib", "miner", "node", "wallet"]
resolver = "2"

[workspace.dependencies]
btclib = { path = "lib" }
miner = { path = "miner" }
node = { path = "node" }
wallet = { path = "wallet" }
