[package]
name = "miner"
version.workspace = true
edition.workspace = true

[dependencies]
btclib = { workspace = true }
tokio = { version = "1.37.0", features = ["full"] }
anyhow = "1.0.98"
clap = { version = "4.5.8", features = ["derive"] }
flume = "0.11.0"
